title: Chee Kai Ling # your name (or website title) here


description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/chee-kai-ling-39625028/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
